name: pda_scanner
description: This is a scanning plug-in for PDA to listen the scanned events and get scanning results.
version: 0.3.0
homepage: https://github.com/hnly766/pda_scanner

environment:
  sdk: ">=3.3.0 < 4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shinow.pda_scanner
        pluginClass: PdaScannerPlugin
